version: "3.7"
services:
  web:
    build:
      context: ./deployment/docker/dev/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      # config nginx
      - ./deployment/nginx/${NAMEPROJECT}.conf:/etc/nginx/conf.d/${NAMEPROJECT}.conf
      # передать папки
      - ./${NAMEPROJECT}:/home/apps/${NAMEPROJECT}
    depends_on:
      - api
  api:
    build:
      context: ./deployment/docker/dev/${NAMEPROJECT}
      dockerfile: php-fpm.docker
    # должны совпадать с путями из nginx
    volumes:
      - ./${NAMEPROJECT}:/home/apps/${NAMEPROJECT}
    environment:
      - PHP_IDE_CONFIG=serverName=api
  postgres:
    build:
      context: ./deployment/docker/dev/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "54321:5432"
    volumes:
      - ./deployment/db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./deployment/postgres-data:/var/lib/postgresql/data