controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

validation:
    resource: ../../src/Validator/
    type: annotation
